stages:
  - test
  - name: deploy
    if: type = push AND fork = false AND env(nuget_key) IS present

jobs:
  include:
  - stage: test
    name: "Demo Run"
    language: csharp
    mono: none
    dotnet: 3.1.200
    dist: xenial
    script:
    - dotnet restore
    - dotnet build
    - cd "DragonFruit.OnionFruit.Status.Tests"
    - dotnet run

  - stage: deploy
    name: "Nuget"
    os: windows
    language: shell
    script:
    - choco install visualstudio2019-workload-netcorebuildtools
    - powershell Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
    - dotnet restore
    - dotnet build -c Release
    - powershell -File Nuget.ps1